# https://teratail.com/questions/253691
version: '3'

services: 
  mysql-db-sample:
    container_name: mysql-db-sample
    build: ./mysql-sample
    ports:
      - 13306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: sample
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql-sample/data:/var/lib/mysql
      - ./mysql-sample/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql-sample/sql:/docker-entrypoint-initdb.d
    tty: true